name: lens2
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - boto3==1.31.85
  - cartopy
  - dask
  - dask-jobqueue
  - geoviews
  - h5netcdf
  - holoviews
  - hvplot
  - jupyter_bokeh
  - jupyterlab
  - netcdf4
  - numpy==2.2.4
  - python==3.10.12
  - xarray
  - watchfiles