apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        env:
        - name: ENV_NAME
          value: {{ .Values.webapp.condaEnv }}
        - name: DASK_CLUSTER_TYPE
          value: 'scheduler:8786'
        imagePullPolicy: {{ .Values.webapp.container.imagePullPolicy }}
        resources:
          limits:
            memory: {{ .Values.webapp.container.memory }}
            cpu: {{ .Values.webapp.container.cpu }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        volumeMounts:
          - mountPath: /home/mambauser/app/LENS2-ncote-dashboard/data_files/
            name: data-files
      volumes:
        - name: data-files
          persistentVolumeClaim:
            claimName: data-files